<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br>
            <h2> <?= $this->view->contact->name; ?></h2>

            <div class="card">
                <div class="card-header">
                    Informações Pessoais
                </div>
                <div class="card-body">
                    <p class="card-text">Telefone: <?= $this->view->contact->phone; ?></p>
                    <p class="card-text">Email: <?= $this->view->contact->email; ?> </p>
                    <a  href="#" class="btn btn-primary"> <i class="fa fa-phone" aria-hidden="true"></i> Ligar agora</a>
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-header">
                    Endereço
                </div>
                <div class="card-body">
                    <h5 class="card-title"><?= $this->view->contact->city; ?> - <?= $this->view->contact->state; ?></h5>
                    <p class="card-text">Cep: <?= $this->view->contact->postal_code; ?></p>
                    <p class="card-text">Rua: <?= $this->view->contact->street; ?> Número <?= $this->view->contact->number; ?> </p>
                    <p class="card-text">Bairro: <?= $this->view->contact->neighbor; ?></p>
                </div>
            </div>
        </div>


        </div>
    </div>
</div>