
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Library</li>
    </ol>
</nav>

<?php if($this->view->success) : ?>
    <?php foreach ($this->view->success as $success): ?>
        <div class="alert alert-success" role="alert">
            <?= $success ?>
        </div>
    <?php endforeach;?>
<?php endif; ?>

<h1>Contatos</h1>
<p><a href="/contact/create"  class="btn btn-success btn-sm">Novo Contato</a></p>

<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Cidade</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->view->contacts as $contact) : ?>
            <tr>
                <td><?= $contact->name ?></td>
                <td><?= $contact->email ?></td>
                <td><?= $contact->phone ?></td>
                <td><?= $contact->city ?></td>
                <td>
                    <a href="/contact/view/<?=$contact->id?>"  class="btn btn-light btn-sm">Visualizar</a>
                    <a href="/contact/update/<?=$contact->id?>" class="btn btn-primary btn-sm">Editar</a>
                    <a href="/contact/delete/<?=$contact->id?>" class="btn btn-danger btn-sm">Deletar</a>
                </td>
            </tr>
        <?php endforeach; ?>


        </tbody>
    </table>
</div>
