<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Library</li>
    </ol>
</nav>

<?php if($this->view->error) : ?>
    <?php foreach ($this->view->error as $error): ?>
        <div class="alert alert-danger" role="alert">
            <?= $error ?>
        </div>
    <?php endforeach;?>
<?php endif; ?>

<?php if($this->view->validation) : ?>
    <?php foreach ($this->view->validation[0] as $v): ?>
        <div class="alert alert-danger" role="alert">
            Validação: <?= $v ?>
        </div>
    <?php endforeach;?>
<?php endif; ?>

<h1>Edtiar Contato | <?= $this->view->contact->id ?></h1>


<form action="/contact/update/<?= $this->view->contact->id ?>" method="post">
    <div class="row">
        <input type="hidden" value="<?= $this->view->contact->id ?>" name="id" id="id">
        <div class="col-md-4">
            <div class="form-group">
                <label for="name">Nome</label>
                <input type="input" id="name" name="name" value="<?= $this->view->contact->name ?>"  class="form-control"
                       placeholder="Nome">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" value="<?= $this->view->contact->email ?>" novalidate placeholder="Email">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="phone">Telefone</label>
                <input type="input" class="form-control" id="phone" name="phone" value="<?= $this->view->contact->phone ?>" required minlength="11"
                       placeholder="Telefone">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="postalcode">Cep</label>
                <input type="input" class="form-control" id="postal_code" name="postal_code"  value="<?= $this->view->contact->postal_code ?>" placeholder="Cep">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="city">Cidade</label>
                <input type="input" class="form-control" id="city" name="city" value="<?= $this->view->contact->city ?>" placeholder="Cidade">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="estate">UF</label>
                <select class="form-control" id="state" name="state">
                    <option <?= $this->view->contact->state == 'RJ' ? 'selected' : '';?> value="RJ">Rio de Janeiro</option>
                    <option <?= $this->view->contact->state == 'SP' ? 'selected' : '';?> value="SP">São Paulo</option>
                    <option <?= $this->view->contact->state == 'MG' ? 'selected' : '';?> value="MG">Minas Gerais</option>
                    <option <?= $this->view->contact->state == 'ES' ? 'selected' : '';?> value="ES" >Espirito Santo</option>
                </select>

            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="street">Logradouro</label>
                <input type="input" class="form-control" id="street" name="street" value="<?= $this->view->contact->street ?>" placeholder="Logradouro">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="number">Número</label>
                <input type="input" class="form-control" id="number" name="number" value="<?= $this->view->contact->number ?>" placeholder="Número">
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label for="neighbor">Bairro</label>
                <input type="input" class="form-control" id="neighbor" name="neighbor" value="<?= $this->view->contact->neighbor ?>"  placeholder="Bairro">
            </div>
        </div>



        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>


    </div>
</form>